# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


    driver.get("http://localhost/Hotel-Management-System/index.php")
    driver.set_window_size(1366, 738)
    driver.find_element(By.CSS_SELECTOR, ".btns:nth-child(2)").click()
    driver.find_element(By.NAME, "Emp_Email").click()
    driver.find_element(By.NAME, "Emp_Email").send_keys("Admin@gmail.com")
    driver.find_element(By.NAME, "Emp_Password").send_keys("1234")
    driver.find_element(By.NAME, "Emp_login_submit").click()
    driver.find_element(By.CSS_SELECTOR, ".pagebtn:nth-child(3)").click()
    driver.switch_to.frame(1)
    driver.find_element(By.NAME, "troom").click()
    dropdown = driver.find_element(By.NAME, "troom")
    dropdown.find_element(By.XPATH, "//option[. = 'GUEST HOUSE']").click()
    driver.find_element(By.NAME, "bed").click()
    dropdown = driver.find_element(By.NAME, "bed")
    dropdown.find_element(By.XPATH, "//option[. = 'Quad']").click()
    driver.find_element(By.NAME, "addroom").click()
  
